// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeidoDemoDb;

#nullable disable

namespace SeidoDemoDb.Migrations
{
    [DbContext(typeof(SeidoDemoDbContext))]
    [Migration("20220310152521_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("SeidoDemoModels.Necklace", b =>
                {
                    b.Property<Guid>("NecklaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("NecklaceID");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar (200)");

                    b.HasKey("NecklaceID");

                    b.ToTable("Necklaces");
                });

            modelBuilder.Entity("SeidoDemoModels.Pearl", b =>
                {
                    b.Property<Guid>("PearlID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("PearlID");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar (200)");

                    b.Property<Guid>("NecklaceID")
                        .HasColumnType("TEXT")
                        .HasColumnName("NecklaceID");

                    b.HasKey("PearlID");

                    b.HasIndex("NecklaceID");

                    b.ToTable("Pearl");
                });

            modelBuilder.Entity("SeidoDemoModels.Pearl", b =>
                {
                    b.HasOne("SeidoDemoModels.Necklace", null)
                        .WithMany("Pearl")
                        .HasForeignKey("NecklaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeidoDemoModels.Necklace", b =>
                {
                    b.Navigation("Pearl");
                });
#pragma warning restore 612, 618
        }
    }
}
